import mongoose from "mongoose";
import dotenv from "dotenv";
dotenv.config({ path: "./src/.env.local" });

const connectDb = async () => {
  try {
    await mongoose.connect(process.env.MONGO_URI, {
      dbName: process.env.MONGODB_DB_NAME
    });
  } catch (err) {
    console.error("MongoDB connection error:", err);
    process.exit(1);
  }
};

const getDocsModel = () => {
  if (mongoose.models.Docs) return mongoose.models.Docs;
  const DocsSchema = new mongoose.Schema({
    technology: { type: String, required: true },
    topics: [{
      slug: String,
      title: String,
      order: Number,
      content: String,
      interviewQuestions: Array,
      practicalTask: Object
    }]
  });
  return mongoose.model("Docs", DocsSchema);
};

const cleanDb = async () => {
  await connectDb();
  const Docs = getDocsModel();
  const allDocs = await Docs.find({});
  
  for (let doc of allDocs) {
    // Filter out undefined orders and keep only the latest topic for each order
    const orderMap = new Map();
    for (let topic of doc.topics) {
      if (topic.order !== undefined && topic.order !== null && !isNaN(topic.order)) {
        // Overwrite so we keep the LAST one (which is the one generated by the new strict framework)
        orderMap.set(topic.order, topic);
      }
    }
    
    // Sort by order
    const cleanTopics = Array.from(orderMap.values()).sort((a,b) => a.order - b.order);
    
    doc.topics = cleanTopics;
    await doc.save();
    console.log(`Cleaned ${doc.technology}: left with ${cleanTopics.length} topics (Orders: ${cleanTopics.map(t=>t.order).join(',')})`);
  }
  process.exit(0);
};

cleanDb();
