import { rewriteAnswers } from './rewriteAnswers.js';

const map = {
  "In your role at Neutrinos, you architected a dynamic, stage-based decision API. Can you walk me through the specific architectural choices you made to handle complex application state logic and role-specific paths?": "Absolutely. I architected the decision API using a state machine pattern driven by a metadata configuration table in our PostgreSQL database. Instead of hardcoding conditional logic for each stage, I defined stages, required roles, and transition criteria as data. When a request came in, the Node.js service would query the current stage, validate the user's role against the stage requirements (like checking if the user had 'Reviewer' privileges for a particular document), and evaluate the payload against the transition rules. This decoupled the business logic from the codebase, allowing product managers to alter workflows simply by updating the configuration via the Strapi admin panel without requiring a new deployment. This drastically reduced the time to market for new client workflows.",

  "For the Domain Scanner project, you constructed a distributed architecture using RabbitMQ for background domain analysis. What were the specific challenges you faced regarding asynchronous task processing, and how did you handle task failures or retries?": "For Domain Scanner, the biggest challenge was dealing with long-running, unpredictable domain analysis tasks that could time out or crash. I used RabbitMQ as the message broker. The producer would publish a 'scan_requested' event to a durable exchange. I configured the consumer queues with explicit manual acknowledgments. If a consumer crashed mid-scan, the unacknowledged message would remain in the queue and be picked up by another worker. For transient failures, like a timeout reaching a third-party DNS API, I implemented a dead-letter exchange (DLX) with a TTL-based retry mechanism. If a task failed 3 times, it was moved to a 'failed_scans' queue where I could manually inspect it. This ensured zero dropped scans even during heavy traffic spikes.",

  "You integrated Redis for high-speed caching and PostgreSQL for data persistence in Domain Scanner. How did you decide what data to cache, and how did you handle cache invalidation?": "I adopted a targeted caching strategy where I only cached data that was computationally expensive to generate but rarely changed, such as the final aggregated scan reports. When a user requested a report, I'd first check Redis. If there was a cache miss, I'd query PostgreSQL, generate the report, and store it in Redis with a TTL of 24 hours to prevent memory bloat. For cache invalidation, whenever a new scan was initiated for a domain, I published a 'cache_invalidate' event. A background worker would intercept this and immediately delete the corresponding Redis keys. This guaranteed that users never saw stale data while significantly reducing the load on the PostgreSQL database during traffic peaks.",

  "At Neutrinos, you contributed to robust policy lifecycle automation systems for enterprise clients like Sunlife PH. How did you ensure data consistency and reliability in these complex processing workflows?": "To ensure data consistency in the Sunlife PH policy workflows, I relied heavily on database transactions and idempotency keys. Every time a policy transition was triggered via our REST API, I required the client to pass a unique idempotency key. My backend would first check if this key already existed in a 'processed_requests' table. If it did, I'd return the cached response. If not, I would initiate a PostgreSQL transaction, update the policy state, insert the idempotency record, and commit. If any step failed, the entire transaction rolled back. This guaranteed that even if the client retried a request due to a network timeout, we would never double-process a policy or end up in an inconsistent state.",

  "You utilized Strapi CMS alongside Node.js for 15+ RESTful APIs. What were the trade-offs of using a headless CMS like Strapi versus building the admin and content management from scratch?": "Using Strapi CMS for the 15+ RESTful APIs allowed me to bypass the tedious process of building out CRUD endpoints and an admin panel from scratch. It saved us weeks of development time and empowered the content team to manage data immediately. However, the trade-off was a loss of fine-grained control and performance overhead. As our business logic grew complex, I had to write custom Strapi controllers and lifecycle hooks that sometimes felt like fighting the framework. Furthermore, Strapi's default ORM queries weren't always optimized for our specific join patterns, which forced me to write raw database queries for our most critical, read-heavy endpoints to maintain performance.",

  "Tell me about a time when you disagreed with a senior engineer or product manager on an architectural decision. How did you navigate the conflict, and what was the outcome?": "During a major refactor, a senior engineer insisted on migrating our monolith straight into microservices, while I advocated for a modular monolith approach first. I felt the microservices overhead would slow down our small team. I navigated this by acknowledging their valid concerns about scalability, but I presented a quantifiable Proof of Concept. I demonstrated how a modular monolith could isolate domains using strict module boundaries in Node.js, providing 80% of the isolation benefits with 20% of the dev-ops overhead. We compromised: we would build it as a modular monolith but deploy it behind an API gateway so we could peel off services later if needed. Ultimately, this saved us months of infrastructure setup and we hit our deadline.",

  "Describe a situation where a critical production issue arose (perhaps related to the \"Beyond the Call of Duty\" award). How did you manage the stress, coordinate with your team, and resolve the issue?": "During a major release, our primary database instance spiked to 100% CPU, bringing down the entire platform. The stress was intense. I immediately jumped on a war-room call, communicated the severity to stakeholders, and paused the CI/CD pipeline. I diagnosed the issue using our APM tools and discovered an unindexed query introduced in the latest PR was causing full table scans. I coordinated with my team: I focused on writing and deploying the index hotfix, while another engineer handled rolling back the application to the previous stable version to restore immediate service. We resolved it in 45 minutes, and afterwards, I led the post-mortem where we implemented automated query analysis in our staging environment.",

  "You worked with cross-functional agile teams at Neutrinos. Can you give an example of how you handled a situation where a dependency from another team was blocking your work?": "I was working on a feature that required a new API endpoint from the core backend team, but they were swamped and pushed it to the next sprint. Instead of just marking my ticket as blocked, I looked at their repository, understood their domain logic, and submitted a pull request with the API endpoint myself. I added comprehensive tests and reached out to their lead engineer, explaining that I wrote the code to unblock my team but was happy to revise it based on their standards. They reviewed it, merged it the next day, and it not only unblocked my work but also fostered a stronger collaborative relationship between our teams.",

  "Tell me about a time when you had to learn a new technology or framework quickly to deliver a project on time. How did you approach the learning process?": "We needed to implement real-time features, and I had to learn WebSockets and Socket.io over a weekend. I started by reading the official documentation to grasp the fundamental concepts of bidirectional communication. Then, instead of just reading tutorials, I built a small, isolated prototype—a basic chat room. Once I had the prototype working, I integrated a simplified version into our staging environment to test it against our authentication middleware. Finally, I documented my findings, including the pitfalls I encountered regarding connection drops and reconnect logic, and shared a brief presentation with the team so they could get up to speed quickly.",

  "Can you describe a time when you received constructive criticism from a peer or manager? How did you respond, and what changes did you make?": "Early in my career, my manager pointed out that my pull requests were often too large, making them difficult to review and increasing the risk of regressions. Initially, I felt a bit defensive, but I realized they were entirely right. I responded by thanking them for the feedback and fundamentally changed my workflow. I started breaking down my work into smaller, logical commits and opening draft PRs earlier in the process. I also began adding detailed descriptions and test plans to every PR. This not only made life easier for my reviewers but actually accelerated the overall merge velocity of the team.",

  "You received the \"Team Player Award\" for strong collaboration. Can you share a specific instance where your collaborative efforts directly impacted a critical project deliverable?": "We were nearing a critical deadline for a client deliverable, and our frontend lead unexpectedly fell ill. The frontend team was struggling to integrate the complex APIs I had built. To ensure we didn't miss the deadline, I stepped outside my backend role. I spent two days pair-programming with the junior frontend developers, helping them debug state management issues and adjust the API payloads on the backend to better suit their UI components. We successfully delivered the project on time. This experience earned me the Team Player Award, as it highlighted my willingness to bridge the gap between frontend and backend to achieve a shared goal.",

  "The \"Beyond the Call of Duty Award\" implies taking ownership beyond your assigned scope. Can you detail the specific production issue you took ownership of, why it was outside your scope, and the steps you took to ensure system uptime?": "Over a holiday weekend, I noticed a critical memory leak alert from our production environment, even though I wasn't on call. I knew this system handled high-value transactions. I took ownership and logged in. I used Node.js memory profiling tools to capture a heap snapshot and discovered that a newly deployed third-party logging library was holding onto request objects. Because I couldn't reach the original author, I wrote a hotfix to temporarily disable the library and fallback to standard logging, tested it locally, and pushed it through our emergency CI pipeline. I stabilized the system and documented the entire incident, which led to the 'Beyond the Call of Duty' recognition.",

  "In managing full-cycle production deployments using CI/CD, PM2, and Nginx for Domain Scanner, how did you ensure zero downtime and handle rollbacks if a deployment failed?": "I set up our CI/CD pipeline using GitHub Actions to automate testing and building. For zero-downtime deployments, I utilized PM2's cluster mode. During a deployment, the pipeline would pull the new code and run `pm2 reload all`. This commanded PM2 to gracefully restart workers one by one, ensuring there was always a process available to handle incoming Nginx traffic. For rollbacks, I configured the pipeline to tag every release. If the post-deployment health check failed, the pipeline would automatically trigger a script to checkout the previous Git tag, rebuild, and reload PM2, restoring the stable state within seconds.",

  "Given your experience with Docker and Kubernetes, how would you approach migrating a legacy monolithic application to a microservices architecture hosted on Kubernetes? What would be your first steps?": "My first step wouldn't be to rewrite everything. I would use the strangler fig pattern. I'd start by containerizing the existing monolith using Docker and deploying it to Kubernetes as a single pod. Then, I would configure an API gateway (like Nginx Ingress or Kong) in front of it. Next, I'd identify the most loosely coupled, stateless domain—perhaps the user notification system—and extract that into a separate microservice. I'd route traffic for notifications to the new service via the API gateway, leaving the rest going to the monolith. I would iteratively repeat this process, slowly strangling the monolith while ensuring continuous delivery.",

  "As a backend-focused engineer, how do you ensure that the APIs you design are developer-friendly and easy for the frontend team to consume?": "I treat APIs as a product where the frontend developers are my users. I always start with an API design contract, usually written in OpenAPI (Swagger), and get frontend sign-off before writing a single line of backend code. I ensure consistent naming conventions, standardized pagination, and predictable, detailed JSON error responses so the frontend can easily map them to UI alerts. Crucially, I always provide a Postman collection and, when possible, a mock server so the frontend team can start building their components immediately without waiting for my backend implementation to be fully complete.",

  "Describe a situation where your technical vision fundamentally contradicted the CTO's architectural mandate, yet you knew their approach would lead to systemic failure. How did you handle the situation, and what was the outcome?": "The CTO wanted to use a NoSQL database for a highly relational financial ledger system to 'move fast'. I knew the lack of ACID compliance and complex joins would eventually cause data corruption. I didn't just argue; I built a small prototype using their NoSQL approach and another using PostgreSQL. I benchmarked both under simulated concurrent transaction loads, demonstrating how the NoSQL approach failed consistency checks under stress. I presented the data objectively. Seeing the empirical evidence of data loss, the CTO agreed to pivot to PostgreSQL. It preserved our relationship and saved the company from a costly architectural rewrite.",

  "You inherit a high-performing team but soon discover a critical 'brilliant jerk' who delivers 50% of the team's output but constantly sabotages psychological safety. The company relies on their knowledge for an upcoming critical launch. Walk me through your action plan.": "Psychological safety is non-negotiable, regardless of output. I would immediately schedule a 1-on-1 with this engineer. I'd acknowledge their technical contributions but provide clear, specific examples of their toxic behavior and how it impacts the team. I would set firm boundaries and outline a PIP (Performance Improvement Plan) focused entirely on behavioral metrics, not code. Simultaneously, I would aggressively de-risk the upcoming launch by pairing them with other engineers to force knowledge transfer and break the silo. If their behavior didn't improve rapidly, I would terminate them, knowing the temporary hit to velocity is worth preserving the long-term health of the entire team.",

  "Tell me about a time you had to reverse a major technical decision that you yourself fiercely advocated for, after realizing it was the wrong path months into implementation.": "I once championed using a bleeding-edge GraphQL federation architecture for a new project. I was convinced it was the future. However, three months in, the complexity of managing the subgraphs and the performance overhead of resolving deeply nested queries crippled our development speed. I realized my mistake. I called an all-hands meeting, owned up to the poor decision, and presented a pragmatic plan to strip out the federation and revert to a simpler RESTful API gateway. It was a humbling experience, but the team appreciated my transparency, and our velocity doubled once we removed the over-engineered architecture.",

  "A critical project is three weeks behind schedule, and the business demands you push the team to work weekends. You know the team is already on the verge of burnout. How do you negotiate with the business to protect your team while delivering value?": "I would gather the concrete data: velocity charts, remaining scope, and current team hours. I'd present this to the business stakeholders, explaining that mandating weekend work produces diminishing returns and increases the risk of critical bugs due to fatigue. Instead of just saying 'no', I would negotiate the scope. I would identify the absolute MVP features required for the launch and propose cutting or delaying the non-essential features. I'd commit to delivering the core value on time during normal hours. By offering a pragmatic trade-off rather than a blank refusal, I can protect my team while still meeting the core business objective.",

  "Walk me through the most catastrophic production outage you were directly responsible for. Don't gloss over the details. What exactly did you break, how long was it down, and what was the systemic fix?": "I ran a migration script that accidentally dropped the primary users table in production instead of staging due to a misconfigured environment variable. The site was instantly down. I immediately declared a severity 1 incident in Slack and halted all automated systems. I accessed the automated AWS RDS snapshots and initiated a point-in-time recovery to five minutes before my script ran. The system was down for 35 minutes. To fix the systemic issue, I implemented strict IAM roles so dev credentials could never access prod databases, required a secondary approver for all destructive migrations, and added a dry-run validation step to our migration pipeline.",

  "Describe a time when you successfully delivered a project exactly to spec, on time, and on budget, but it completely failed to achieve its business objectives. What did you learn?": "I built a complex internal analytics dashboard exactly to the product manager's specifications. It had real-time graphs, advanced filtering, and sub-second latency. It launched on time and under budget. However, a month later, telemetry showed zero active users. I interviewed the stakeholders and learned the tool was too complex; they just wanted a weekly automated PDF report emailed to them. I learned that executing perfectly on the wrong requirements is still a failure. Now, I always insist on understanding the underlying user problem and validating the solution with real users before writing code.",

  "Have you ever had to pull the plug on a project that consumed months of engineering effort? How did you justify the sunken cost to the team and keep morale high?": "Yes, we spent four months building a custom billing engine. Midway, a new SaaS product launched that solved our exact problem for a fraction of the cost of our ongoing engineering time. It was a tough pill to swallow. I called a meeting and presented the financial and strategic analysis. I acknowledged the hard work and explicitly praised the technical elegance of what we had built, emphasizing that the code was good, but the business context had changed. I framed pulling the plug as a strategic win because it freed us to work on our core product differentiators rather than reinventing a commodity.",

  "Tell me about a legacy system modernization project you led that failed or went significantly over budget. What were the hidden complexities that you underestimated?": "I led a migration from an old monolithic PHP app to Node.js. It went significantly over budget. I severely underestimated the hidden, undocumented business logic buried in 10-year-old spaghetti code. We estimated based on the visible API endpoints, completely missing the scheduled cron jobs and direct database triggers that the PHP app relied on. The project took twice as long because we essentially had to reverse-engineer the business rules line-by-line. The lesson I learned is to never estimate legacy migrations without first doing a comprehensive audit of the data layer and background processes, not just the application code.",

  "You discover that a senior executive is quietly bypassing data privacy protocols (e.g., GDPR/CCPA compliance) to accelerate a feature launch, exposing user data. You brought it up, but were told to drop it. What is your next move?": "Data privacy is a legal and ethical hard line. After my verbal pushback was ignored, I documented my concerns in writing, detailing how the implementation violated GDPR/CCPA, and emailed it to the executive, cc'ing myself. I requested explicit, written confirmation that they wanted to proceed despite the compliance risks. If they still insisted without involving legal, I would escalate the matter to the company's Data Protection Officer or Legal Counsel, and if necessary, the CEO. I cannot write code that intentionally violates user privacy laws, even if instructed by a superior.",

  "Your team is building an algorithmic feature, and you realize the training data introduces a severe bias against a minority demographic, but fixing it will delay the launch by a quarter. How do you handle this?": "I would immediately pause the launch and escalate the issue to product and business leadership. Launching an algorithm with severe demographic bias is not just a technical flaw; it's a reputational and ethical disaster. I would present the data proving the bias and clearly state that the quarter delay is the necessary cost of fixing it. I would propose an interim solution, such as releasing a rules-based, non-algorithmic version of the feature while we retrain the model with balanced data. I will not sign off on deploying an inherently discriminatory system into production.",

  "You are asked to implement a 'dark pattern' in the UI designed to trick users into subscribing to an expensive tier they likely don't need. How do you push back?": "I would refuse to implement it, but I wouldn't just say 'no'. I would initiate a conversation with the product manager to understand the underlying goal, which is usually increasing revenue or conversions. I would explain that while dark patterns might cause a short-term spike in subscriptions, they inevitably lead to massive churn, chargebacks, and brand damage in the long run. I would then propose an alternative, ethical design that highlights the genuine value of the expensive tier and uses A/B testing to optimize conversion rates honestly. If they still mandate the dark pattern, I would escalate to leadership.",

  "Your resume states you 'architected a microservices migration'. Many candidates claim this when they just wrote one service. Precisely what was your role in defining the domain boundaries, inter-service communication protocols, and handling distributed transactions?": "In the microservices migration, I wasn't just writing endpoints. I was responsible for the domain-driven design. I analyzed our monolith and defined the bounded contexts—like separating 'Billing' from 'User Management'. I established the inter-service communication protocol, choosing gRPC for internal synchronous calls due to its performance, and RabbitMQ for asynchronous event-driven updates. For distributed transactions, I implemented the Saga pattern using choreography, ensuring that if a payment failed in the Billing service, a compensating transaction would automatically fire to revert the corresponding state in the Order service.",

  "You mention 'scaling the application to handle 10x traffic'. Walk me through the exact bottlenecks you hit. What broke first? The database, the network, the compute? How did you profile it?": "When we hit 10x traffic, the first thing to break was the database. We were maxing out connection pools, and query latency spiked. I used New Relic and pg_stat_statements to profile the database and found that a few complex read queries were causing the bottleneck. I implemented a Redis caching layer for those specific queries and added read replicas to offload the read traffic from the primary master node. Once the database stabilized, our network bandwidth became the next bottleneck, which I mitigated by implementing aggressive payload compression and optimizing our API responses to only return essential fields.",

  "You led a 'complete agile transformation' according to your resume. Agile transformations often fail due to cultural resistance. Who was your biggest detractor, and how did you win them over?": "My biggest detractor during the agile transformation was a brilliant, veteran principal engineer who viewed Jira and daily standups as micromanagement and a waste of time. I didn't force the process on them. Instead, I sat down and asked them what their biggest pain point was. They hated being constantly interrupted by PMs asking for status updates. I showed them how maintaining their Jira board accurately would act as an information radiator, eliminating the need for those interruptions. Once they experienced a week with zero status-update interruptions, they became the biggest champion of the agile process.",

  "Your resume highlights 'reducing cloud costs by 40%'. Was this just right-sizing instances, or did you have to fundamentally re-architect how the application consumed resources? Give me an example of a structural change you made.": "While right-sizing instances helped, the real 40% cost reduction came from a fundamental architectural shift. We had a fleet of EC2 instances running 24/7 to process background video rendering jobs, which were highly bursty. We were paying for idle compute 80% of the time. I re-architected this pipeline to use AWS Lambda for the lightweight coordination tasks and AWS Batch with Spot Instances for the heavy rendering workloads. The system would dynamically scale up Spot Instances only when a queue of videos built up, and scale to zero when idle. This structural shift to event-driven, ephemeral compute drastically slashed our AWS bill."
};

const run = async () => {
    try {
        console.log("Rewriting answers for round-1...");
        await rewriteAnswers('round-1', map);
        console.log("Done.");
        process.exit(0);
    } catch (err) {
        console.error("Error:", err);
        process.exit(1);
    }
};

run();
