import { rewriteAnswers } from './rewriteAnswers.js';

const map = {
  "You have a memory leak in a Node.js production service. A heap snapshot shows a massive Retained Size but a small Shallow Size for an array of closures. Explain what is happening and how V8's context allocation causes this.": "In a recent project, I encountered this exact scenario where our Node.js production service was experiencing a memory leak. When I analyzed the heap snapshot, I noticed a small shallow size but a massive retained size on an array of closures. I realized this was because of how V8 handles context allocation. When I create closures that share a lexical environment, V8 allocates variables used by those closures into a shared 'Context' object on the heap. In my code, I had a large object referenced by just one of the closures. Even though the other closures didn't directly use that large object, they all shared the same Context. Because I was holding onto references of those other closures in an array, the garbage collector couldn't free the shared Context, meaning the large object remained in memory. To fix this, I made sure to manually nullify the reference to the large object as soon as I no longer needed it, which immediately allowed the GC to clean up the Context and stopped the memory leak.",
  
  "Your Node.js API experiences severe latency spikes every few minutes. Tracing reveals it's caused by the V8 Garbage Collector's Mark-Sweep phase. How do you optimize the application to reduce Old Space GC pauses?": "I experienced severe latency spikes in my Node API and tracked it down to the V8 Garbage Collector's Mark-Sweep phase. The Mark-Sweep cycle is a 'stop-the-world' event, and my Old Space was filling up too quickly with objects that survived the initial Scavenger GC. To optimize this, I took a multi-step approach. First, I refactored the hot paths in my code to reduce unnecessary object allocations, ensuring short-lived objects could be quickly cleaned up in the New Space without ever being promoted. Second, I realized I was caching large data structures directly in memory, which was bloating the Old Space. I migrated that cache to Redis, which drastically reduced the memory footprint. Finally, for the objects I absolutely had to retain, I implemented an Object Pool to reuse instances instead of constantly destroying and recreating them. As a temporary buffer while deploying these fixes, I also slightly increased the `--max-old-space-size` flag. These changes completely eliminated the GC-induced latency spikes.",
  
  "A Node.js service using a C++ image processing addon is crashing with OOM, but V8 heap snapshots show memory usage is well under the limit. How do you diagnose and fix this?": "I ran into a really tricky issue where my Node.js service crashed with OOM errors while processing images, but my V8 heap snapshots showed memory was perfectly fine. I immediately suspected an unmanaged memory leak outside the V8 heap, as I was using a C++ addon and Node Buffers, which are allocated off-heap. To diagnose it, I couldn't rely on Node's inspector. Instead, I attached `valgrind` and used OS-level profiling tools which confirmed the C++ addon was accumulating un-freed memory. To fix the issue, I modified the C++ addon's code. Instead of manually allocating memory and forgetting it, I bound the lifecycle of the unmanaged off-heap memory to a JavaScript object using `Napi::Buffer` and registered a cleanup callback using `napi_add_finalizer`. This allowed V8's garbage collector to properly trigger the C++ destructor whenever the corresponding JavaScript object was garbage collected, completely resolving the OOM crashes.",
  
  "When using the Node.js `cluster` module, explain the bottlenecks of IPC (Inter-Process Communication) and why it's a bad idea to use `process.send()` for high-frequency, large payload synchronization between workers.": "In a clustered architecture I was building, I initially tried using `process.send()` to sync state across my worker processes. I quickly discovered a massive bottleneck. Node's IPC relies on Unix Domain Sockets or named pipes, and every time I called `process.send()`, the runtime had to serialize my large payloads into JSON and deserialize them on the receiving end. Because serialization is synchronous, it blocked the event loop on both the sending and receiving workers, driving my CPU usage through the roof and causing immense latency on high-frequency syncs. I realized it's a terrible idea to use IPC for heavy data sharing. I refactored the system to use Redis as an external, shared datastore. The workers just queried Redis for the state instead of passing huge messages through Node's IPC, which freed up the event loop and dramatically improved performance.",
  
  "You need to perform heavy matrix multiplication in Node.js. Compare using Worker Threads with `SharedArrayBuffer` vs spawning child processes. What are the synchronization risks?": "When I needed to implement a heavy matrix multiplication algorithm in Node.js, I had to choose between Worker Threads and child processes. I decided against child processes because passing large matrices back and forth would require IPC serialization, which is incredibly slow and CPU-intensive. Instead, I used Worker Threads because they run in the same process and allow me to pass a `SharedArrayBuffer`. This gave me zero-copy memory access, making the math exponentially faster. However, the tradeoff was synchronization. Because multiple threads were reading and writing to the exact same block of memory simultaneously, I faced severe race conditions. To mitigate this, I had to be extremely careful and manually manage locks using the `Atomics` API, specifically relying on `Atomics.wait` and `Atomics.add` to ensure thread-safe operations. It was complex to implement, but the performance gains for the matrix math were totally worth it.",
  
  "In a clustered Node.js application, each worker creates its own database connection pool. If you have 40 pods, each with 4 workers, and a pool size of 20, you overwhelm the database with 3200 connections. How do you architect a solution to this?": "I faced this exact problem while scaling up a microservice. I had 40 Kubernetes pods, each running 4 Node cluster workers, and each worker initialized a database pool of 20 connections. We ended up hammering our PostgreSQL database with over 3,200 open connections, causing connection exhaustion and crashing the database. To fix it, I re-architected how we handle DB connectivity. First, I deployed PgBouncer as a centralized connection proxy in front of the database. This allowed all 3,200 client connections to be multiplexed down to a small, manageable number of actual backend database connections. Concurrently, I reviewed our application code and drastically reduced the pool size per Node worker from 20 down to 2. Because Node handles I/O asynchronously, a worker rarely needs 20 parallel connections anyway. This combination entirely solved our database connection limits.",
  
  "An application uses Worker Threads to offload a CPU-heavy task. The main thread sends tasks to workers via `worker.postMessage()`. Suddenly, the main thread's event loop blocks. What likely caused this?": "I encountered an issue where offloading tasks to Worker Threads ironically froze my main thread. I was passing a massive, deeply nested dataset from the main thread to the worker using `worker.postMessage()`. I realized that `postMessage` relies on the structured clone algorithm, which synchronously traverses and copies the entire object. The serialization process itself was so heavy that it blocked the main event loop before the worker even had a chance to start processing. To fix it, I refactored the data structure to use an `ArrayBuffer`. By passing it as a 'Transferable Object', I essentially transferred memory ownership from the main thread directly to the worker. This meant zero serialization and zero copying. The main thread's event loop immediately became unblocked, and the application ran smoothly again.",
  
  "Explain the race condition that occurs during JWT Refresh Token Rotation when a client fires multiple concurrent API requests. How do you solve it without forcing the user to log out?": "While implementing JWT Refresh Token Rotation, I discovered a nasty race condition. When my front-end app loaded, it fired off several API requests simultaneously. If the access token was expired, all those requests would concurrently try to use the same refresh token to get a new session. The first request would succeed, rotating the tokens and invalidating the original refresh token. A fraction of a millisecond later, the second request would hit the backend with that now-invalidated token. My system's theft-detection assumed the token was stolen and aggressively revoked all access, forcing the legitimate user to log out. To solve this smoothly, I built a 'grace period' into the backend cache. When a refresh token is used, instead of instantly destroying it, I keep it valid in Redis for a 10-second window, mapped to the newly generated token. Any concurrent requests arriving within that window are safely served the exact same new token pair, preserving the rotation security without breaking the user's session.",
  
  "Describe the 'Backend-for-Frontend' (BFF) pattern in the context of OAuth2. Why is it considered more secure than the standard Authorization Code Flow with PKCE for Single Page Applications?": "I recently upgraded an architecture to use the Backend-for-Frontend (BFF) pattern for OAuth2 specifically to harden our security posture. Previously, our SPA used the standard Authorization Code Flow with PKCE. While PKCE prevents authorization code interception, it ultimately results in the SPA receiving the Access and Refresh tokens. If we ever suffered an XSS vulnerability, malicious JavaScript could easily steal those tokens from localStorage or memory. I implemented the BFF pattern to remove tokens from the browser entirely. Now, I have a lightweight Node.js layer serving the SPA. The BFF handles the OAuth2 handshake and securely stores the tokens on the server. It only issues a strictly scoped, `HttpOnly`, `SameSite` encrypted cookie back to the browser. The SPA just makes requests using that cookie, completely oblivious to the actual OAuth tokens. This guarantees that even if an XSS attack occurs, the tokens are physically inaccessible to the attacker.",
  
  "How do you implement a 'Split Token' architecture to mitigate both XSS and CSRF attacks simultaneously for an API consumed by a web browser?": "I implemented a 'Split Token' architecture to provide bulletproof protection against both XSS and CSRF for our web API. When a user logs in, I don't send the full JWT back to the client. Instead, I split the token in half on the backend. I place the sensitive signature portion into an `HttpOnly`, `Secure` cookie, which makes it totally immune to XSS since JavaScript can't read it. I send the header and payload portion directly in the API response, which the front-end stores in memory or localStorage. To make an authenticated request, the front-end code attaches the payload via the Authorization header, while the browser naturally includes the signature cookie. On the backend, my middleware intercepts both, concatenates them back into a single JWT, and verifies it. This means an attacker would somehow have to execute a simultaneous XSS attack to get the payload AND a CSRF attack to utilize the cookie, which makes stealing a session practically impossible.",
  
  "An attacker intercepts a valid JWT and replays the request to a sensitive endpoint multiple times before the token expires. How do you prevent Replay Attacks using JWT claims?": "I tackled a vulnerability in our financial application where an attacker could intercept a valid JWT and repeatedly fire requests at a sensitive money-transfer endpoint before the token expired. To prevent this replay attack, I started injecting a `jti` (JWT ID) claim into the token, giving every token a cryptographically unique identifier. I then implemented a caching layer using Redis on the backend. Whenever a non-idempotent request was successfully processed, I extracted the `jti` from the token and stored it in Redis, setting its TTL to match the token's exact `exp` (expiration) timestamp. My middleware checks every incoming request against Redis; if it sees a `jti` that already exists in the cache, it instantly rejects the request as a replay attack. This effectively forced the token to be single-use for sensitive actions and completely closed the vulnerability.",
  
  "In a microservices architecture, Service A calls Service B on behalf of a user. If Service A's access token is compromised, an attacker can access Service B. How do you prevent this lateral movement using OAuth2 Token Exchange (RFC 8693)?": "In a complex microservices mesh I designed, I was concerned about lateral movement: if Service A was breached, the attacker could take the user's access token and exploit it against Service B, Service C, or any downstream dependency. To stop this, I implemented OAuth2 Token Exchange (RFC 8693). I configured the network so that Service A is absolutely forbidden from simply forwarding the user's original token. Instead, when Service A needs to call Service B, it contacts the Authorization Server, presents the original token, and requests a token exchange. The Auth Server validates the request and mints a brand-new, highly restricted token that contains a specific audience claim (`aud`) set strictly for Service B. If an attacker compromises Service A and steals its tokens, they can't pivot and attack Service C, because the token will be explicitly rejected outside of its scoped path. This strictly enforced the principle of least privilege across our services."
};

const run = async () => {
  try {
    await rewriteAnswers('round-3', map);
    console.log('Successfully updated round-3 questions.');
    process.exit(0);
  } catch (err) {
    console.error(err);
    process.exit(1);
  }
};

run();
