import { rewriteAnswers } from "./rewriteAnswers.js";

const updatedQuestionsMap = {
  "How do you handle schema design in MongoDB for a highly read-intensive application vs a write-intensive one?": "When I design for a read-intensive app, I heavily favor embedding data. For example, in a blog application I built, I embedded the comments directly inside the post document so the frontend could render the entire page with a single query. This avoids the overhead of multiple network trips. On the flip side, for a write-intensive system like an IoT telemetry aggregator I worked on, I used referencing. Since sensors were constantly firing updates, embedding would mean constantly growing documents and moving them on disk. So I normalized the data, minimized the indexes to keep write overhead low, and only updated tiny, specific documents.",
  "Can you explain the ESR (Equality, Sort, Range) rule for creating compound indexes in MongoDB?": "I strictly follow the ESR rule when building compound indexes to make sure my queries run as fast as possible. First, I put the fields I'm querying for exact matches—Equality. Then, I add the fields I'm using to Sort the results. Finally, I append fields used for Range queries, like greater-than or less-than filters. By structuring it this way, I ensure the database can use the index to immediately jump to the right records, return them already sorted, and then scan the range, without having to load extra data into memory to sort it.",
  "Can you explain a complex aggregation pipeline you have built? How did you optimize it?": "In one project, I had to build a reporting dashboard that aggregated millions of user interactions. I built a pipeline starting with a `$match` stage to filter out inactive users immediately, which drastically reduced the working set size. Then, I used a `$lookup` to join user profile data, followed by an `$unwind` and finally a `$group` stage to calculate daily averages. To optimize it, I made sure my `$match` fields were covered by indexes, and I intentionally placed the `$project` and `$match` stages as early as possible so that I wasn't passing massive amounts of unnecessary data through the expensive `$lookup` and `$group` stages.",
  "How do you approach data modeling for 1-to-many relationships in MongoDB? When would you use referencing versus embedding?": "My rule of thumb is to look at the boundaries of the relationship. If it's a 'one-to-few' relationship where the child data is always viewed with the parent—like a user and their multiple shipping addresses—I embed it. It's faster and cleaner. But if it's 'one-to-many' and unbound, like a popular user with millions of followers, I absolutely use referencing. If I tried to embed millions of followers, I'd quickly hit MongoDB's 16MB document limit and cause massive performance degradation every time the document needs to grow.",
  "Describe how to handle transactions in MongoDB. What are the performance implications?": "I try to avoid multi-document transactions in MongoDB whenever possible by designing my schema around single-document updates, which are inherently atomic. However, when I worked on a financial ledger feature where atomicity across multiple accounts was absolutely critical, I used MongoDB's multi-document ACID transactions via our replica set. I made sure to keep the transactions as short as possible because they lock documents and incur a noticeable performance penalty and overhead on the coordinator node.",
  "In your \"Domain Scanner\" project, you used PostgreSQL for persistence. Why did you choose it over MongoDB for this specific use case?": "For the Domain Scanner, I specifically chose PostgreSQL because the domain risk assessment data was highly relational and required strict data integrity. I needed robust foreign keys to link scan results to domains and organizations, and I needed strong ACID compliance to ensure no scan data was left in an inconsistent state. The ability to write complex ad-hoc SQL queries for reporting across multiple linked tables made a relational model the perfect fit, whereas MongoDB would have forced me to do complex application-side joins.",
  "Explain how you manage migrations and schema changes in a production PostgreSQL database without downtime.": "When I perform migrations in production, I always ensure they are backward-compatible. If I'm adding a column, I add it with a default value or allow nulls so the current application version doesn't break. If I need to rename or move data, I'll create the new column or table, implement double-writing in the application so both old and new schemas are updated, backfill the historical data, and only then flip the read path. I also make sure to use `CONCURRENTLY` when creating indexes so I don't lock the tables for writes during the build process, and I schedule heavy migrations during off-peak hours.",
  "What are CTEs (Common Table Expressions) and when would you use them over subqueries?": "I use CTEs, or WITH clauses, all the time to make my complex SQL queries actually readable and maintainable. Instead of nesting five layers of subqueries that are impossible to decipher, I define logical blocks at the top of my query. I also specifically use recursive CTEs when I'm dealing with hierarchical data. For example, I built an organizational chart feature where I used a recursive CTE to traverse the manager-employee tree from top to bottom in a single query.",
  "Can you describe how isolation levels work in PostgreSQL and how they prevent dirty reads, non-repeatable reads, and phantom reads?": "PostgreSQL defaults to Read Committed, meaning my query only sees data that was committed before it started, preventing dirty reads. If I need a stronger guarantee, like when generating a financial report, I use Repeatable Read to ensure the data doesn't change during my transaction. When absolute correctness is required, I use the Serializable level. Postgres handles this beautifully using Serializable Snapshot Isolation (SSI), which tracks read/write dependencies using predicate locks and safely aborts any transactions that would result in phantom reads, without locking up the whole database.",
  "How do you optimize a slow-performing SQL query? What steps do you take when analyzing the output of EXPLAIN ANALYZE?": "The first thing I do is run `EXPLAIN ANALYZE` to get the actual execution plan. I immediately look for `Seq Scan` on large tables, which tells me the database is scanning the whole table instead of using an index. I also check for high-cost joins or if the database is using a `Bitmap Heap Scan` instead of an `Index Scan`. Based on that, I'll add the missing indexes, rewrite the query to be more efficient, or run `VACUUM ANALYZE` to update the planner's statistics so it chooses a better execution path.",
  "You integrated Redis for high-speed caching in \"Domain Scanner\". What specific caching patterns (e.g., Cache-Aside, Write-Through) did you implement?": "I primarily implemented a Cache-Aside, or lazy loading, pattern. When a request came in for domain metadata, my app would first check Redis. If it was a miss, it queried PostgreSQL, returned the data, and then wrote it to Redis with a TTL. For a few highly critical settings, I used a Write-Through pattern where the application updated both the database and the cache simultaneously, trading a bit of write latency for the guarantee that the cache would never serve stale data.",
  "How do you handle cache invalidation, especially in a distributed system where data is updated frequently?": "Cache invalidation is notoriously tricky, so I use a layered approach. First, I always set appropriate TTLs on my Redis keys so data naturally expires. For data that updates unpredictably and needs immediate consistency, I use an event-driven architecture. In one system, whenever a record was updated in the DB, the service published a message to RabbitMQ, and all cache nodes subscribed to that topic would immediately drop or update the relevant cache keys.",
  "What data structures in Redis have you used beyond simple key-value strings, and for what use cases?": "I use Redis as much more than just a string cache. I use Hashes to store object properties like user sessions, so I can update single fields without rewriting the whole object. I heavily use Sorted Sets for building real-time leaderboards and rate limiters because of their O(log(N)) score-based ordering. I've used Lists for simple queueing and timelines, and I've even used Bitmaps for highly memory-efficient analytics, like tracking daily active users across millions of accounts.",
  "Describe the memory eviction policies in Redis. How do you choose the right one for a caching layer?": "When configuring Redis as a pure cache, I generally set the eviction policy to `allkeys-lru` or `allkeys-lfu`. This ensures that when Redis hits its max memory, it automatically drops the least recently or least frequently used keys to make room for new data. If I'm mixing cache data with more persistent session data in the same instance, I use `volatile-lru`, which tells Redis to only evict keys that have an explicit TTL set, protecting my permanent keys from being deleted.",
  "If your Redis instance suddenly goes down, how does your application handle the failure? Do you have fallback mechanisms?": "I design my applications so that Redis is never a single point of failure. I wrap all my cache calls in a try-catch block and implement a circuit breaker pattern. If Redis times out or throws connection errors, the circuit trips open, and my application seamlessly degrades to querying the primary database directly. It logs the failure for my alerting system and periodically attempts to ping Redis so the circuit can close again once the service is restored.",
  "You used RabbitMQ for asynchronous task processing in the \"Domain Scanner\". Can you explain the difference between a direct, topic, and fanout exchange?": "In my RabbitMQ setups, I use a Direct exchange when I want a message routed to a queue based on an exact routing key match, like sending an email. I use a Topic exchange for pub/sub patterns where consumers can use wildcards—for instance, one queue might listen for `scan.domain.*` while another listens for `scan.*.error`. And I use a Fanout exchange when I need to broadcast a message to every single bound queue blindly, like a system-wide configuration update.",
  "How do you handle message retries and dead-letter queues (DLQ) in RabbitMQ for failed domain scanning tasks?": "For the Domain Scanner, I configured a Dead Letter Exchange (DLX) on my main task queues. If a scanning task failed, my consumer would reject (`nack`) the message without requeuing it, or if it timed out based on its TTL, RabbitMQ automatically routed it to the DLQ. I then had a separate consumer monitoring the DLQ that would either attempt retries using an exponential backoff strategy or alert me for manual inspection if the failure was fatal.",
  "What happens if a consumer crashes while processing a message? How does RabbitMQ ensure message durability and delivery?": "I always use manual acknowledgments (`ack`) in my consumers. If my consumer pulls a message, starts processing, and then crashes before sending the `ack`, the RabbitMQ broker detects the severed connection. Because it never got the acknowledgment, it assumes the message failed and immediately requeues it, delivering it to the next available consumer. To ensure complete durability, I also configure both my queues and my messages to be durable so they survive a full broker restart.",
  "How do you scale consumers in RabbitMQ when the queue starts building up rapidly?": "I use the competing consumers pattern. When I see queue depth increasing via my monitoring tools, I simply spin up more instances of my consumer microservice. Because RabbitMQ automatically round-robins the messages among all active consumers listening to that queue, the load is immediately distributed. In my Kubernetes environments, I automate this by using an HPA (Horizontal Pod Autoscaler) that watches the RabbitMQ queue length metric and scales the pods up and down as needed.",
  "Explain the concept of prefetch count (QoS) in RabbitMQ and how it impacts consumer performance and load balancing.": "I tune the prefetch count to control how many unacknowledged messages RabbitMQ pushes to a consumer at once. If I don't set it, a fast consumer might grab all the messages in the queue, leaving other consumers completely idle, which ruins load balancing. If I set it to 1, it's perfectly fair, but the network latency of waiting for an `ack` before sending the next message kills throughput. I usually benchmark and set a moderate prefetch value—say 10 or 20—to keep the consumer busy without hoarding messages.",
  "How do you choose between RDB and AOF in Redis for a high-write throughput cache that occasionally needs disaster recovery?": "If I only needed basic disaster recovery, I might stick to RDB because those point-in-time snapshots are incredibly fast to load on restart, though I'd risk losing recent data. If I needed zero data loss, I'd use AOF to log every write, but that creates huge files and slow restarts. For a high-write environment, I actually use the hybrid approach available in newer Redis versions. I configure it to take periodic RDB snapshots and append the incremental AOF logs to them. This gives me the fast restart times of RDB with the high durability of AOF.",
  "Explain what happens when Redis runs out of memory, and how different eviction policies affect a distributed lock implementation.": "When Redis hits its `maxmemory` limit, its behavior depends on the policy I've set. If it's `noeviction`, it simply rejects new writes. If it's `allkeys-lru`, it starts deleting the oldest keys. This is extremely dangerous if I'm using Redis for distributed locks, because the eviction policy might silently delete an active lock key, allowing multiple services to grab the same lock and corrupting my data. To prevent this, I ensure my locks always have strict TTLs and I put them on a dedicated Redis instance configured with `noeviction` or `volatile-*` so active locks are never randomly evicted.",
  "How does Redis replication handle network partitions, and what is the role of the repl-backlog-size?": "When a network partition happens, the master keeps accepting writes and queues those commands in its replication backlog buffer. When the network heals and the replica reconnects, it asks for a partial resync (PSYNC) to just get the missed commands. However, if the downtime was too long and my `repl-backlog-size` was too small, the buffer overflows. The master then forces a full resynchronization, which means generating a full snapshot and transferring it over the network—a massive I/O hit. I always tune the backlog size based on my expected write volume and the maximum partition time I want to absorb without a full sync.",
  "What are the consequences of choosing a monotonically increasing field (like an ObjectId or timestamp) as a MongoDB shard key?": "I would never use a monotonically increasing field like a timestamp as a shard key. If I do, every single new insert gets routed to the exact same chunk on the exact same shard, creating a massive hot spot. I lose all the write-scaling benefits of sharding because only one node is doing the work. Furthermore, the cluster will constantly have to pause and rebalance those chunks across the other shards, creating severe background I/O overhead. I'd use a hashed shard key instead to guarantee even write distribution.",
  "How would you design a MongoDB shard key for a multi-tenant SaaS application where some tenants have 100x more data than others?": "I wouldn't use just the `tenant_id` as the shard key, because those massive tenants would create 'jumbo chunks'—chunks that exceed the maximum size, can't be split, and get stuck on a single shard. Instead, I'd design a compound shard key like `{ tenant_id: 1, document_id: 1 }` or `{ tenant_id: 1, created_at: 1 }`. This approach ensures that a single massive tenant's data is safely distributed across multiple chunks and shards, while still allowing my application to perform highly targeted and efficient queries since the `tenant_id` prefix is still present in the key.",
  "Explain the role of the mongos router in a sharded cluster and what happens if a query doesn't include the shard key.": "The `mongos` router is the traffic cop; my application connects to it instead of the shards directly. It caches metadata from the config servers to know exactly which shard holds which chunk of data. If my query includes the shard key, the `mongos` routes it directly to the single correct shard. But if I issue a query without the shard key, the `mongos` is forced to do a 'scatter-gather'—it broadcasts the query to every single shard in the cluster, waits for them all to respond, and merges the results. This is highly inefficient and ruins the scalability of the cluster.",
  "What is MVCC (Multi-Version Concurrency Control) in Postgres, and what is the 'bloat' problem associated with it?": "I love MVCC because it allows my concurrent transactions to read and write without locking each other. When I update or delete a row in Postgres, it doesn't overwrite it; it creates a new version of the row and marks the old one as a 'dead tuple'. However, this causes the 'bloat' problem. If I have a highly active table and those dead tuples accumulate faster than the `AUTOVACUUM` process can clean them up, my table size balloons, disk space is wasted, and sequential scans slow to a crawl because they have to read past all that dead data.",
  "How does Postgres transaction ID (XID) wraparound happen, and what are the catastrophic consequences if not monitored?": "Postgres uses 32-bit transaction IDs, meaning it can only track about 4 billion transactions before the IDs wrap around back to zero. To handle this, it divides the ID space into 'past' and 'future' and uses vacuuming to 'freeze' old rows so they are permanently visible to all transactions. If I don't monitor my autovacuum performance and a wraparound happens before old tuples are frozen, older data suddenly appears to have a 'future' transaction ID and becomes entirely invisible to my application. It's a catastrophic data loss scenario, which is why Postgres will forcefully shut itself down to prevent it if it gets too close.",
  "Explain the difference between Read Committed and Serializable isolation levels in PostgreSQL, and how Serializable prevents Phantom Reads.": "When I use the default Read Committed level, my query only sees data committed before it started, but if I run the same query twice in a transaction, the results might change if someone else committed an update. When I need absolute consistency, I use Serializable, which guarantees the results are identical to running the transactions one after another. I appreciate how Postgres implements this using Serializable Snapshot Isolation (SSI)—instead of locking the tables and killing concurrency, it tracks predicate locks on read/write dependencies and safely aborts any transaction that would have caused anomalies like phantom reads.",
  "Why should you use a connection pooler like PgBouncer instead of having your application servers connect directly to PostgreSQL?": "Unlike some databases that use lightweight threads, Postgres forks a brand new OS process for every single connection. Each process consumes a lot of memory—often 10MB or more—and CPU for context switching. If I have a bunch of application servers opening hundreds of direct connections, I'll quickly exhaust the database server's memory or hit the connection limit. I always put PgBouncer in front to multiplex thousands of lightweight application connections down to a small, manageable pool of actual database connections.",
  "What is 'connection starvation' in a microservices architecture, and how can max connection limits cascade into a full system outage?": "I've seen connection starvation happen when multiple microservices share a database without centralized pooling. A traffic spike in Service A causes it to greedily consume all available database connections up to the max limit. When Service B tries to connect, it times out. If Service B doesn't have proper circuit breakers, its own internal thread pools fill up waiting for the database, causing Service B to crash. This ripples through the architecture as other services waiting on Service B also fail, turning a localized connection issue into a cascading, full-system outage.",
  "In a Node.js serverless environment (like AWS Lambda) connecting to an RDS instance, how do you handle connection pooling?": "Serverless environments are a nightmare for traditional databases because functions scale out rapidly and tear down constantly, creating thousands of ephemeral direct connections that overwhelm RDS. Standard in-memory Node poolers like `pg-pool` don't work because they reset per container. To solve this, I always deploy an external proxy layer, like AWS RDS Proxy or PgBouncer. The Lambda functions can rapidly open and close connections to the proxy without overhead, while the proxy maintains a stable, long-lived pool of connections to the RDS instance.",
  "What is a Dead Letter Queue (DLQ) and what specific scenarios should trigger a message being routed there?": "I use a Dead Letter Queue as a safety net for messages that my system simply cannot process. I configure my broker to route a message to the DLQ in three specific scenarios: first, if the message has been retried too many times and exceeded its max retry count; second, if the message is a 'poison pill' with a malformed payload that my parser rejects outright; and third, if the message sits in the queue so long that its TTL expires. This keeps my main queue flowing and isolates the problem messages for me to investigate.",
  "How do you handle a 'poison pill' message that crashes the consumer process every time it is parsed?": "A poison pill is dangerous because it crashes the consumer before I can explicitly `nack` it or increment a retry counter in the app. The broker sees the disconnect, assumes a network failure, and redelivers the message to another consumer, crashing that one too. To break the loop, I ensure my application performs strict schema validation on the raw payload *before* attempting complex processing. Alternatively, I configure the broker itself, like RabbitMQ with quorum queues, to track delivery attempts internally and automatically route the message to the DLQ after a few failed deliveries.",
  "Design an automated replay mechanism for a DLQ where messages failed due to a temporary downstream API outage.": "When I design a DLQ, I make sure the messages contain metadata about why they failed and the original timestamp. For an automated replay system, I'd build a cron job or a lightweight consumer that periodically reads the DLQ. If it sees the failure reason was a transient error like a `503 Downstream Unavailable`, it holds the message. Once a health check to the downstream API passes, it pushes the message into a 'retry' exchange with exponential backoff. If the failure was a non-transient `400 Bad Request`, it leaves the message in the DLQ for manual developer intervention."
};

async function run() {
  try {
    await rewriteAnswers("round-4", updatedQuestionsMap);
    console.log("Rewrite completed successfully!");
    process.exit(0);
  } catch (error) {
    console.error("Error running rewrite:", error);
    process.exit(1);
  }
}

run();
